name: Build, push and run the image to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Create .env file
        run: |
          echo "DB_HOST=host.docker.internal" > server/.env
          echo "DB_USER=root" >> server/.env
          echo "DB_PASSWORD=7000882564a@A" >> server/.env
          echo "DB_DATABASE=crudmysql" >> server/.env

      - name: Build Docker Image
        run: |
          cd server
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejsserver:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejsserver:latest

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nodejsserver:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop nodejs-server || true
          docker rm nodejs-server || true

      - name: Run Docker Container
        run: docker run --name nodejs-server -p 8001:8001 --env-file server/.env -d ${{ secrets.DOCKERHUB_USERNAME }}/nodejsserver:latest
